/**
 * Jira Unsuckify — content script.
 *
 * Releases the per-column (and per-swimlane) scroll containers on the
 * modernised Jira Cloud board so every column shows its full content height
 * and the board area scrolls as one.
 *
 * Everything this script does is CSS. It sets attributes on <body> and injects
 * one generated stylesheet. Turning it off removes both, which restores the
 * original layout with no reload.
 *
 * See docs/dom-notes.md for where the selectors came from and what was
 * measured on a live board.
 */
(function () {
  "use strict";

  const CONFIG = globalThis.JBU_SELECTORS;
  if (!CONFIG) return;

  const { SELECTORS_VERSION, SELECTORS, REQUIRED, BOARD_PATH_RE } = CONFIG;

  const STYLE_ID = "jbu-generated-style";
  const ATTR = {
    active: "data-jbu-active",
    sticky: "data-jbu-sticky",
    debug: "data-jbu-debug",
    contentVisibility: "data-jbu-content-visibility",
  };

  const DEFAULTS = {
    enabled: true,
    stickyHeaders: true,
    contentVisibility: false,
    debug: false,
    selectorOverrides: {},
  };

  let settings = { ...DEFAULTS };
  let isActive = false;
  let lastStatus = null;
  let lastHref = location.href;
  let evaluateTimer = null;
  let observer = null;

  /* ------------------------------------------------------------------ *
   * Selectors
   * ------------------------------------------------------------------ */

  /** Returns the user's override for a selector key, or the shipped default. */
  function sel(key) {
    const override = settings.selectorOverrides && settings.selectorOverrides[key];
    return typeof override === "string" && override.trim() ? override.trim() : SELECTORS[key];
  }

  function log(...args) {
    if (settings.debug) console.log("[jira-unsuckify]", ...args);
  }

  /* ------------------------------------------------------------------ *
   * Stylesheet
   * ------------------------------------------------------------------ */

  /**
   * Builds the whole stylesheet from the current selectors.
   *
   * Two details here are not obvious and are load-bearing:
   *
   * 1. Wrapper elements get `min-height: max-content`, not `height: auto`.
   *    Jira sizes the board through grid rows declared as `minmax(0, 1fr)`.
   *    An `fr` track with a zero minimum collapses to zero height as soon as
   *    its container stops having a definite height, so `height: auto` alone
   *    makes the whole board vanish into a 32px strip.
   *
   * 2. The board wrapper keeps `overflow: auto` on both axes. It already owns
   *    horizontal scrolling, and it becomes the board's single vertical
   *    scroller. Setting `overflow-y: visible` there would be ignored anyway:
   *    CSS forces an axis back to `auto` when the other axis is not `visible`.
   */
  function buildCss() {
    const root = `body[${ATTR.active}="true"]`;
    const S = {
      boardWrapper: sel("boardWrapper"),
      cell: sel("cell"),
      cellScroller: sel("cellScroller"),
      columnHeader: sel("columnHeader"),
      swimlaneScroller: sel("swimlaneScroller"),
      card: sel("card"),
    };

    return `
/* Generated by Jira Unsuckify. Selectors version ${SELECTORS_VERSION}. */

/* The column scroller stops being a scroller and grows to fit its cards. */
${root} ${S.cellScroller} {
  overflow: visible !important;
  height: auto !important;
  max-height: none !important;
  min-height: 0 !important;
}

/* The column itself grows to fit header + cards + create button. */
${root} ${S.cell} {
  height: auto !important;
  max-height: none !important;
  min-height: max-content !important;
}

/* Same treatment for swimlanes when grouping is on. */
${root} ${S.swimlaneScroller} {
  overflow: visible !important;
  height: auto !important;
  max-height: none !important;
  min-height: max-content !important;
}

/* The unnamed flex/grid wrappers between the board wrapper and the columns.
   They have no test id of their own, so they are reached structurally.
   align-items: start stops every column being stretched to the tallest one. */
${root} ${S.boardWrapper} > div,
${root} ${S.boardWrapper} > div > div {
  height: auto !important;
  max-height: none !important;
  min-height: max-content !important;
  align-items: start !important;
}

/* The board wrapper stays the scroll container, now for both axes. */
${root} ${S.boardWrapper} {
  overflow-x: auto !important;
  overflow-y: auto !important;
}

/* Sticky column headers. The box-shadow is a solid block painted upwards to
   cover the board wrapper's top padding, which cards would otherwise show
   through as they scroll under the header. */
${root}[${ATTR.sticky}="true"] ${S.columnHeader} {
  position: sticky !important;
  top: 0 !important;
  z-index: 5 !important;
  background: var(--jbu-header-bg, var(--ds-surface, #ffffff)) !important;
  box-shadow: 0 -32px 0 0 var(--jbu-header-bg, var(--ds-surface, #ffffff)) !important;
}

/* Optional performance mitigation for very large boards. Off by default: it
   costs accurate scrollbar sizing and can make in-page find miss cards. */
${root}[${ATTR.contentVisibility}="true"] ${S.card} {
  content-visibility: auto;
  contain-intrinsic-size: auto 260px;
}

/* Debug outlines. */
${root}[${ATTR.debug}="true"] ${S.boardWrapper} {
  outline: 2px solid var(--jbu-debug-board) !important;
  outline-offset: -2px;
}
${root}[${ATTR.debug}="true"] ${S.cell} {
  outline: 1px dashed var(--jbu-debug-cell) !important;
}
${root}[${ATTR.debug}="true"] ${S.cellScroller} {
  outline: 1px dashed var(--jbu-debug-scroller) !important;
}
${root}[${ATTR.debug}="true"] ${S.swimlaneScroller} {
  outline: 2px dashed var(--jbu-debug-swimlane) !important;
}
`;
  }

  function applyStyle() {
    let style = document.getElementById(STYLE_ID);
    if (!style) {
      style = document.createElement("style");
      style.id = STYLE_ID;
      (document.head || document.documentElement).appendChild(style);
    }
    const css = buildCss();
    if (style.textContent !== css) style.textContent = css;
  }

  function removeStyle() {
    const style = document.getElementById(STYLE_ID);
    if (style) style.remove();
  }

  /* ------------------------------------------------------------------ *
   * Measurement
   * ------------------------------------------------------------------ */

  /**
   * Sticky headers need an opaque background or cards show through them.
   * Jira's own background colour comes from a CSS custom property that is not
   * set on the header, so the nearest painted ancestor colour is used instead.
   */
  function measureHeaderBackground() {
    const wrapper = document.querySelector(sel("boardWrapper"));
    let node = wrapper;
    while (node && node !== document.documentElement) {
      const bg = getComputedStyle(node).backgroundColor;
      if (bg && bg !== "transparent" && !/rgba\(\s*0,\s*0,\s*0,\s*0\s*\)/.test(bg)) {
        document.body.style.setProperty("--jbu-header-bg", bg);
        return bg;
      }
      node = node.parentElement;
    }
    const fallback = getComputedStyle(document.body).backgroundColor;
    document.body.style.setProperty("--jbu-header-bg", fallback);
    return fallback;
  }

  /* ------------------------------------------------------------------ *
   * Page and selector checks
   * ------------------------------------------------------------------ */

  function isBoardUrl() {
    return BOARD_PATH_RE.test(location.pathname);
  }

  /**
   * Every required selector must match at least one element. If any of them
   * misses, Jira has changed its DOM and we refuse to activate rather than
   * leaving the board half-styled.
   */
  function healthCheck() {
    const missing = REQUIRED.filter((key) => !document.querySelector(sel(key)));
    return { ok: missing.length === 0, missing };
  }

  /* ------------------------------------------------------------------ *
   * Activate / deactivate
   * ------------------------------------------------------------------ */

  function activate() {
    applyStyle();
    const body = document.body;
    body.setAttribute(ATTR.active, "true");
    body.setAttribute(ATTR.sticky, settings.stickyHeaders ? "true" : "false");
    body.setAttribute(ATTR.debug, settings.debug ? "true" : "false");
    body.setAttribute(ATTR.contentVisibility, settings.contentVisibility ? "true" : "false");
    measureHeaderBackground();
    isActive = true;
  }

  function deactivate() {
    if (!document.body) return;
    const body = document.body;
    Object.values(ATTR).forEach((attr) => body.removeAttribute(attr));
    body.style.removeProperty("--jbu-header-bg");
    removeStyle();
    isActive = false;
  }

  /* ------------------------------------------------------------------ *
   * Status reporting
   * ------------------------------------------------------------------ */

  function report(status, missing) {
    const key = status + "|" + (missing || []).join(",");
    if (key === lastStatus) return;
    lastStatus = key;
    const payload = {
      type: "jbu-status",
      status,
      missing: missing || [],
      selectorsVersion: SELECTORS_VERSION,
    };
    try {
      chrome.runtime.sendMessage(payload, () => void chrome.runtime.lastError);
    } catch (_) {
      /* Extension context torn down during a reload. Nothing to do. */
    }
    log("status:", status, missing && missing.length ? missing : "");
  }

  /* ------------------------------------------------------------------ *
   * Main decision
   * ------------------------------------------------------------------ */

  function evaluate() {
    if (!document.body) return;

    if (!settings.enabled) {
      if (isActive) deactivate();
      report("disabled");
      return;
    }

    if (!isBoardUrl()) {
      if (isActive) deactivate();
      report("not-a-board");
      return;
    }

    const health = healthCheck();
    if (!health.ok) {
      // The board may simply not have rendered yet, so this is not an error on
      // its own — the observer will call back when the DOM changes. It only
      // becomes a real signal once the board wrapper exists but its children
      // do not, which is what "selector-broken" means here.
      const wrapperPresent = !!document.querySelector(sel("boardWrapper"));
      if (isActive) deactivate();
      report(wrapperPresent ? "selector-broken" : "waiting", health.missing);
      return;
    }

    // Idempotent: re-running while already active only refreshes the style and
    // the measured background, which is what we want after an SPA navigation.
    activate();
    report("active");
  }

  function scheduleEvaluate() {
    if (evaluateTimer) return;
    evaluateTimer = setTimeout(() => {
      evaluateTimer = null;
      evaluate();
    }, 200);
  }

  /* ------------------------------------------------------------------ *
   * Observation
   * ------------------------------------------------------------------ */

  function startObserver() {
    if (observer) return;
    observer = new MutationObserver(() => {
      // A content script runs in an isolated world, so patching
      // history.pushState here would not see the page's own calls. Jira
      // re-renders on every in-app navigation, so the URL is checked from the
      // same mutation callback instead.
      if (location.href !== lastHref) {
        lastHref = location.href;
        lastStatus = null;
        log("navigated to", location.href);
      }
      scheduleEvaluate();
    });
    observer.observe(document.documentElement, { childList: true, subtree: true });
  }

  /* ------------------------------------------------------------------ *
   * Settings
   * ------------------------------------------------------------------ */

  function readSettings() {
    return new Promise((resolve) => {
      chrome.storage.sync.get(DEFAULTS, (stored) => {
        if (chrome.runtime.lastError) {
          resolve({ ...DEFAULTS });
          return;
        }
        resolve({ ...DEFAULTS, ...stored });
      });
    });
  }

  chrome.storage.onChanged.addListener((changes, area) => {
    if (area !== "sync") return;
    let touched = false;
    Object.keys(changes).forEach((key) => {
      if (key in DEFAULTS) {
        settings[key] = changes[key].newValue;
        touched = true;
      }
    });
    if (!touched) return;
    lastStatus = null;
    evaluate();
  });

  chrome.runtime.onMessage.addListener((message, _sender, sendResponse) => {
    if (message && message.type === "jbu-query-status") {
      const health = healthCheck();
      sendResponse({
        enabled: settings.enabled,
        isBoardUrl: isBoardUrl(),
        active: isActive,
        missing: health.missing,
        selectorsVersion: SELECTORS_VERSION,
        url: location.href,
      });
      return true;
    }
    return false;
  });

  window.addEventListener("popstate", () => {
    lastStatus = null;
    scheduleEvaluate();
  });

  /* ------------------------------------------------------------------ *
   * Start
   * ------------------------------------------------------------------ */

  async function start() {
    settings = await readSettings();
    startObserver();
    evaluate();
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", start, { once: true });
  } else {
    start();
  }
})();
